name: haring-street
services:
  db:
    image: postgres
    reserved_name: recipes_db
    debug:
      volumes:
        volume:
          host_path: postgres
          mount_path: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    interfaces:
      main:
        port: 5432
